"""init

Revision ID: 97cb380f3265
Revises: 
Create Date: 2026-06-18 20:46:48.388322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97cb380f3265'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('imagen_url', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estados_pedido',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_estados_pedido_orden'), 'estados_pedido', ['orden'], unique=False)
    op.create_table('formas_pago',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('es_alergeno', sa.Boolean(), nullable=False),
    sa.Column('stock_cantidad', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('unidad_medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('simbolo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('simbolo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('direcciones_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('linea1', sa.Text(), nullable=False),
    sa.Column('linea2', sa.Text(), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('codigo_postal', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_entrega_usuario_id'), 'direcciones_entrega', ['usuario_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagen_url', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unidad_venta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['unidad_venta_id'], ['unidad_medidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['rol_codigo'], ['roles.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_codigo')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('estado_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('forma_pago_codigo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('pagado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), server_default='50.00', nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('total >= 0', name='ck_pedidos_total_nonnegative'),
    sa.ForeignKeyConstraint(['direccion_id'], ['direcciones_entrega.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['forma_pago_codigo'], ['formas_pago.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_direccion_id'), 'pedidos', ['direccion_id'], unique=False)
    op.create_index(op.f('ix_pedidos_estado_codigo'), 'pedidos', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_pedidos_forma_pago_codigo'), 'pedidos', ['forma_pago_codigo'], unique=False)
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_table('productos_categoria',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'categoria_id')
    )
    op.create_table('productos_ingredientes',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('es_removible', sa.Boolean(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), server_default='1.00', nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medidas.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'ingrediente_id')
    )
    op.create_table('detalles_pedido',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('nombre_snapshot', sa.Text(), nullable=False),
    sa.Column('precio_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_snap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('personalizacion', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad >= 1', name='ck_detalles_pedido_cantidad_min'),
    sa.CheckConstraint('precio_snapshot >= 0', name='ck_detalles_pedido_precio_snapshot_nonnegative'),
    sa.CheckConstraint('subtotal_snap >= 0', name='ck_detalles_pedido_subtotal_snap_nonnegative'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pedido_id', 'producto_id')
    )
    op.create_table('historial_estados_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('estado_desde', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('estado_hacia', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estado_desde'], ['estados_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['estado_hacia'], ['estados_pedido.codigo'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_pedido_estado_hacia'), 'historial_estados_pedido', ['estado_hacia'], unique=False)
    op.create_index(op.f('ix_historial_estados_pedido_pedido_id'), 'historial_estados_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_historial_estados_pedido_usuario_id'), 'historial_estados_pedido', ['usuario_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mp_preference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mp_init_point', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('mp_payment_id', sa.BigInteger(), nullable=True),
    sa.Column('mp_merchant_order_id', sa.BigInteger(), nullable=True),
    sa.Column('mp_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('mp_status_detail', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payment_method_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('external_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_pagos_pedido_id'), 'pagos', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_pedido_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_historial_estados_pedido_usuario_id'), table_name='historial_estados_pedido')
    op.drop_index(op.f('ix_historial_estados_pedido_pedido_id'), table_name='historial_estados_pedido')
    op.drop_index(op.f('ix_historial_estados_pedido_estado_hacia'), table_name='historial_estados_pedido')
    op.drop_table('historial_estados_pedido')
    op.drop_table('detalles_pedido')
    op.drop_table('productos_ingredientes')
    op.drop_table('productos_categoria')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_forma_pago_codigo'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estado_codigo'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_direccion_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('usuarios_roles')
    op.drop_table('productos')
    op.drop_index(op.f('ix_direcciones_entrega_usuario_id'), table_name='direcciones_entrega')
    op.drop_table('direcciones_entrega')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('unidad_medidas')
    op.drop_table('roles')
    op.drop_table('ingredientes')
    op.drop_table('imagenes')
    op.drop_table('formas_pago')
    op.drop_index(op.f('ix_estados_pedido_orden'), table_name='estados_pedido')
    op.drop_table('estados_pedido')
    op.drop_table('categorias')
    # ### end Alembic commands ###
